# Generated by Django 4.1.7 on 2023-06-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_thread_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
