# Generated by Django 4.1.7 on 2023-06-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/post_images/'),
        ),
    ]
