# Generated by Django 4.1.7 on 2023-06-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_chat_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
